### ISSUE TITLE
app searches ledger binary strictly at /usr/bin/ledger

### ISSUE THREAD

**Issue by ignis32** [slashdotdash/node-ledger-rest#5]
Conditions:

```
Ubuntu-14.04-x86_64.
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
```

ledger binary was installed  at  /usr/bin/ledger.

App returns "execvp(): No such file or directory\n"  on "/version"  request.

Strace shows the following:

```
[pid 13200] execve("/usr/local/bin/ledger", ["/usr/local/bin/ledger", "--version"], [/* 21 vars */]) = -1 ENOENT (No such file or directory)
[pid 13200] write(19, "\2\0\0\0", 4 <unfinished ...>

```

 App does not try any other locations for the ledger binary

`ln -s /usr/bin/ledger /usr/local/bin/ledger`  fixes the problem fore me,

but I think that it would be nice if app could find the binary using PATH  without this workaround.

Cheers!

**Comment by slashdotdash** [comment]
@ignis32 You can provide the path to the Ledger binary as a configuration option to `LedgerRest`. 

The config object is passed through to the [ledger-cli](https://github.com/slashdotdash/node-ledger) library.

``` js
var LedgerRest = require('ledger-rest').LedgerRest;

var server = new LedgerRest({ 
  binary: '/usr/local/bin/ledger',
  file: 'path/to/ledger/journal/file.dat'
});
```

I have no plans to add support for using the PATH variable, but am happy to accept a PR.
